### ISSUE TITLE
Should we remove the Netlify warnings with pull requests

### ISSUE THREAD

**Issue by timotheenivalis** [wamwiki/wamwiki.github.io#94]
Netlify does not work with the current code so we deploy using github actions, but there is a netlify check before we can merge pull requests. 
I think it is a good idea to have warnings and checks and even perhaps mandatory review for pull requests, but the checks are just not the right ones. We should look into fixing that.

**Comment by JulienGAMartin** [comment]
I removed the netlify app in the repository which should have fixed the problem
