### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by matthewwolak** [wamwiki/wamwiki.github.io#95]
The website link to the Contribution Guidelines is broken and the [file](https://github.com/wamwiki/wamwiki.github.io/blob/master/content/en/docs/Contribution%20guidelines/EXCLUDEFORNOW_index.mdNO) seemed to have been given a NULL extension to prevent it from rendering into the site (b2a186b49f4391d5213b1b49f37022d53409d320).

Was this done because it is still the Hugo template and needs to be edited for WAMwiki users?

I will start making some basic instructions for contributors in this file to offer some guidance on how to contribute.

**Comment by timotheenivalis** [comment]
Thanks for pointing that out. Yes, we broke the file waiting to have time to customize it. It is great if you can get started on this!

**Comment by timotheenivalis** [comment]
Hi, I put back the guideline page: https://wildanimalmodels.org/docs/contribution-guidelines/. 
I put minimal instructions based on my first experience creating tutorial content, but it still needs some work about exactly how one goes from Rmd files to a webpage. I aim to work more on that. 
Other people may want to write more about more general aspects of contributions or something else.
